# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = "Python для сетевых инженеров"
copyright = "2015-2022, Natasha Samoylenko"
author = "Natasha Samoylenko"


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.imgconverter",
    "sphinx_inline_tabs",
    "sphinx_copybutton",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "ru"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "furo"
# html_sidebars = {
#    "**": ["about.html", "searchbox.html", "localtoc.html", "navigation.html"]
# }

html_title = "Python для сетевых инженеров"
html_theme_options = {
    "prev_next_buttons_location": "both",
    "navigation_with_keys": True,
    "top_of_page_button": None,
    # "announcement": "",
    "light_css_variables": {
        "color-brand-primary": "#336790",  # "blue"
        "color-brand-content": "#336790",
    },
    "dark_css_variables": {
        "color-brand-primary": "#E5B62F",  # "yellow"
        "color-brand-content": "#E5B62F",
    },
}


# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
html_last_updated_fmt = ""

# -- Options for LaTeX output ---------------------------------------------


latex_engine = 'xelatex'
latex_elements = {
    'fontpkg': r'''
\documentclass[a4paper]{article}
\usepackage[12pt]{extsizes}
\usepackage[margin=1.0in]{geometry}
\usepackage{polyglossia}
\setcounter{secnumdepth}{0}
\setdefaultlanguage{russian}
\setotherlanguage{english}
\usepackage{fontspec}
\defaultfontfeatures{Scale=MatchLowercase}
\setmainfont{DejaVu Sans}
\setsansfont{DejaVu Serif}
\setmonofont{DejaVu Sans Mono}
''',
    'preamble': r'''
\setcounter{tocdepth}{2}
\usepackage[titles]{tocloft}
\cftsetpnumwidth {1.25cm}\cftsetrmarg{1.5cm}
\setlength{\cftchapnumwidth}{0.75cm}
\setlength{\cftsecindent}{\cftchapnumwidth}
\setlength{\cftsecnumwidth}{1.25cm}
''',
    'fncychap': r'\usepackage[Bjornstrup]{fncychap}',
    'printindex': r'\footnotesize\raggedright\printindex',
    'figure_align': 'H',
}

# -- Options for epub output -------------------------------------------------

epub_theme = 'epub'
epub_basename = 'Python для сетевых инженеров'
epub_author = 'Наташа Самойленко'
epub_cover = ('cover.png', 'epub_cover_template.html')
# epub_publisher = 'https://natenka.io/'
epub_scheme = 'url'
# epub_identifier = 'https://natenka.io/'
# epub_pre_files = [('index.html', 'Python для сетевых инженеров')]
#epub_post_files = [('install.html', 'Installing Sphinx'),('develop.html', 'Sphinx development')]
# epub_exclude_files = ['_static/README.md']
epub_fix_images = False
epub_max_image_width = 0
epub_show_urls = 'inline'
epub_use_index = False
# epub_guide = (('toc', 'index.html', 'Table of Contents'),)


